### ISSUE TITLE
Web.Config file incorrect

### ISSUE THREAD

**Issue by taflad33** [burki169/kbvault#9]
Hello,

in the detailed instructions, it says to change code in the lines `<connectionStrings> <add name="KbVaultEntities" connectionString="metadata=res:///KBVaultEntityModel.csdl|res:///KBVaultEntityModel.ssdl|res://*/KBVaultEntityModel.msl;provider=System.Data.SqlClient;provider connection string=&quot;data source=.\sqlexpress;initial catalog=kbvault;integrated security=True;multipleactiveresultsets=True;application name=EntityFramework&quot;" providerName="System.Data.EntityClient" /> </connectionStrings>` but these lines do not appear in the file.

**Comment by burki169** [comment]
Thanx for the heads up. Update the wiki. 
https://github.com/burki169/kbvault/wiki/How-To-Edit-The-Web.config-File
